name: Manual Workflow Trigger

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the person'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'Home location'
        required: false
        default: 'San Francisco, CA'

jobs:
  manual_trigger:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Run manual trigger
      run: |
        echo "Hello, ${{ github.event.inputs.name }}!"
        echo "Your home is ${{ github.event.inputs.home }}."